local addonName, RaidMount = ...
RaidMount.mountInstances = RaidMount.mountInstances or {}  -- Ensure it's always a table

RaidMount.mountInstances = {
   { mountName = "Ashes of Al'ar", itemID = 32458, mountID = 155, raidName = "Tempest Keep", expansion = "The Burning Crusade", bossName = "Kael'thas Sunstrider", dropRate = "~1%", difficulty = "Normal", location = "Netherstorm" },
{ mountName = "Azure Drake", itemID = 44151, mountID = 248, raidName = "Eye of Eternity", expansion = "Wrath of the Lich King", bossName = "Malygos", dropRate = "~1%", difficulty = "Normal", location = "Borean Tundra" },
{ mountName = "Black Drake", itemID = 44224, mountID = 250, raidName = "The Obsidian Sanctum", expansion = "Wrath of the Lich King", bossName = "Sartharion", dropRate = "~2%", difficulty = "Normal 10", location = "Dragonblight" },
{ mountName = "Twilight Drake", itemID = 44228, mountID = 251, raidName = "The Obsidian Sanctum", expansion = "Wrath of the Lich King", bossName = "Sartharion", dropRate = "~2%", difficulty = "Normal 25", location = "Dragonblight" },
{ mountName = "Drake of the South Wind", itemID = 63128, mountID = 439, raidName = "Throne of the Four Winds", expansion = "Cataclysm", bossName = "Al'Akir", dropRate = "~1%", difficulty = "Normal", location = "Uldum" },
{ mountName = "Pureblood Fire Hawk", itemID = 69122, mountID = 441, raidName = "Firelands", expansion = "Cataclysm", bossName = "Ragnaros", dropRate = "~1%", difficulty = "Normal", location = "Mount Hyjal" },
{ mountName = "Flametalon of Alysrazor", itemID = 69823, mountID = 464, raidName = "Firelands", expansion = "Cataclysm", bossName = "Alysrazor", dropRate = "~1%", difficulty = "Normal", location = "Mount Hyjal" },
{ mountName = "Astral Cloud Serpent", itemID = 85555, mountID = 517, raidName = "Mogu'shan Vaults", expansion = "Mists of Pandaria", bossName = "Elegon", dropRate = "~1%", difficulty = "Normal", location = "Kun-Lai Summit" },
{ mountName = "Clutch of Ji-Kun", itemID = 94230, mountID = 537, raidName = "Throne of Thunder", expansion = "Mists of Pandaria", bossName = "Ji-Kun", dropRate = "~1%", difficulty = "Normal", location = "Isle of Thunder" },
{ mountName = "Spawn of Horridon", itemID = 93666, mountID = 536, raidName = "Throne of Thunder", expansion = "Mists of Pandaria", bossName = "Horridon", dropRate = "~1%", difficulty = "Normal", location = "Isle of Thunder" },
{ mountName = "Felsteel Annihilator", itemID = 130140, mountID = 751, raidName = "Hellfire Citadel", expansion = "Warlords of Draenor", bossName = "Archimonde", dropRate = "~1%", difficulty = "Mythic", location = "Tanaan Jungle" },
{ mountName = "Ironhoof Destroyer", itemID = 131650, mountID = 624, raidName = "Blackrock Foundry", expansion = "Warlords of Draenor", bossName = "Blackhand", dropRate = "~1%", difficulty = "Mythic", location = "Gorgrond" },
{ mountName = "Felblaze Infernal", itemID = 146676, mountID = 774, raidName = "The Nighthold", expansion = "Legion", bossName = "Gul'dan", dropRate = "~1%", difficulty = "Normal", location = "Suramar" },
{ mountName = "Hellfire Infernal", itemID = 146675, mountID = 773, raidName = "The Nighthold", expansion = "Legion", bossName = "Gul'dan", dropRate = "~1%", difficulty = "Mythic", location = "Suramar" },
{ mountName = "Abyss Worm", itemID = 147821, mountID = 784, raidName = "Tomb of Sargeras", expansion = "Legion", bossName = "Mistress Sassz'ine", dropRate = "~1%", difficulty = "Normal", location = "Broken Shore" },
{ mountName = "G.M.O.D.", itemID = 168738, mountID = 1128, raidName = "Battle of Dazar'alor", expansion = "Battle for Azeroth", bossName = "High Tinker Mekkatorque", dropRate = "~1%", difficulty = "Mythic", location = "Zuldazar" },
{ mountName = "Glacial Tidestorm", itemID = 168935, mountID = 1129, raidName = "Battle of Dazar'alor", expansion = "Battle for Azeroth", bossName = "Lady Jaina Proudmoore", dropRate = "~1%", difficulty = "Mythic", location = "Zuldazar" },
{ mountName = "Vengeance", itemID = 188763, mountID = 1450, raidName = "Sanctum of Domination", expansion = "Shadowlands", bossName = "Sylvanas Windrunner", dropRate = "~1%", difficulty = "Mythic", location = "The Maw" },
{ mountName = "Sanctum Gloomcharger", itemID = 188769, mountID = 1451, raidName = "Sanctum of Domination", expansion = "Shadowlands", bossName = "The Nine", dropRate = "~1%", difficulty = "Normal", location = "The Maw" },
{ mountName = "Zereth Overseer", itemID = 188772, mountID = 1478, raidName = "Sepulcher of the First Ones", expansion = "Shadowlands", bossName = "The Jailer", dropRate = "~1%", difficulty = "Mythic", location = "Zereth Mortis" },
{ mountName = "Anu'relos, Flame's Guidance", itemID = 220235, mountID = 2211, raidName = "Amirdrassil, the Dream's Hope", expansion = "Dragonflight", bossName = "Fyrakk", dropRate = "~1%", difficulty = "Mythic", location = "Emerald Dream" },
{ mountName = "Ascendant Skyrazor", itemID = 2219, mountID = 2223, raidName = "Nerub-ar Palace", expansion = "The War Within", bossName = "Queen Ansurek", dropRate = "~1%", difficulty = "Mythic", location = "Azj-Kahet" },
{ mountName = "Sureki Skyrazor", itemID = 2223, mountID = 2219, raidName = "Nerub-ar Palace", expansion = "The War Within", bossName = "Queen Ansurek", dropRate = "~1%", difficulty = "Normal", location = "Azj-Kahet" },
{ mountName = "Onyxian Drake", itemID = 49636, mountID = 382, raidName = "Onyxia’s Lair", expansion = "Wrath of the Lich King", bossName = "Onyxia", dropRate = "~1%", difficulty = "Normal", location = "Dustwallow Marsh" },
{ mountName = "Mimiron's Head", itemID = 45693, mountID = 304, raidName = "Ulduar", expansion = "Wrath of the Lich King", bossName = "Yogg-Saron (No Keepers)", dropRate = "~1%", difficulty = "Normal", location = "The Storm Peaks" },
{ mountName = "Invincible's Reins", itemID = 50818, mountID = 363, raidName = "Icecrown Citadel", expansion = "Wrath of the Lich King", bossName = "The Lich King", dropRate = "~1%", difficulty = "Normal", location = "Icecrown" },
{ mountName = "Experiment 12-B", itemID = 78919, mountID = 445, raidName = "Dragon Soul", expansion = "Cataclysm", bossName = "Ultraxion", dropRate = "~1%", difficulty = "Normal", location = "Caverns of Time" },
{ mountName = "Reins of the Blazing Drake", itemID = 77067, mountID = 442, raidName = "Dragon Soul", expansion = "Cataclysm", bossName = "Deathwing", dropRate = "~1%", difficulty = "Normal", location = "Caverns of Time" },
{ mountName = "Life-Binder’s Handmaiden", itemID = 77069, mountID = 444, raidName = "Dragon Soul", expansion = "Cataclysm", bossName = "Deathwing", dropRate = "~1%", difficulty = "Heroic", location = "Caverns of Time" },
{ mountName = "Kor'kron Juggernaut", itemID = 104253, mountID = 522, raidName = "Siege of Orgrimmar", expansion = "Mists of Pandaria", bossName = "Garrosh Hellscream", dropRate = "~1%", difficulty = "Mythic", location = "Vale of Eternal Blossoms" },
{ mountName = "Shackled Ur'zul", itemID = 152901, mountID = 858, raidName = "Antorus, the Burning Throne", expansion = "Legion", bossName = "Argus the Unmaker", dropRate = "~1%", difficulty = "Mythic", location = "Antoran Wastes" },
{ mountName = "Ny'alotha Allseer", itemID = 174872, mountID = 1322, raidName = "Ny'alotha, the Waking City", expansion = "Battle for Azeroth", bossName = "N’Zoth the Corruptor", dropRate = "~1%", difficulty = "Mythic", location = "Uldum/Vale of Eternal Blossoms" },
{ mountName = "Carcinized Zereth Steed", itemID = 190771, mountID = 1508, raidName = "Sepulcher of the First Ones", expansion = "Shadowlands", bossName = "The Jailer", dropRate = "~1%", difficulty = "Heroic", location = "Zereth Mortis" },
{ mountName = "Blue Drake", itemID = 43952, mountID = 247, raidName = "Eye of Eternity", expansion = "Wrath of the Lich King", bossName = "Malygos", dropRate = "~1%", difficulty = "Normal", location = "Borean Tundra" },
{ mountName = "Grand Black War Mammoth", itemID = 44083, mountID = 256, raidName = "Vault of Archavon", expansion = "Wrath of the Lich King", bossName = "Any Boss", dropRate = "~1%", difficulty = "Normal", location = "Wintergrasp" },
{ mountName = "Fiery Warhorse", itemID = 30480, mountID = 136, raidName = "Karazhan", expansion = "The Burning Crusade", bossName = "Attumen the Huntsman", dropRate = "~1%", difficulty = "Normal", location = "Deadwind Pass" },
{ mountName = "The Big G", itemID = 999999, mountID = 2222, raidName = "Liberation of Undermine", expansion = "The War Within", bossName = "Chrome King Gallywix", dropRate = "~1%", difficulty = "Mythic", location = "Undermine" },
{ mountName = "Midnight's Eternal Reins", itemID = 142236, mountID = 841, raidName = "Return to Karazhan", expansion = "Legion", bossName = "Attumen the Huntsman", dropRate = "~1%", difficulty = "Mythic", location = "Deadwind Pass" }

}

