name: Full Addon Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Fetch versions response
        run: |
          curl -s -H "x-api-key: ${{ secrets.CURSEFORGE_TOKEN }}" https://wow.curseforge.com/api/game/versions > response.json
          cat response.json

      - name: Fetch latest Retail game version ID
        id: get-retail-id
        run: |
          curl -s -H "x-api-key: ${{ secrets.CURSEFORGE_TOKEN }}" https://wow.curseforge.com/api/game/versions | \
            jq '[.[] | select(.flavor=="wow_retail" and (.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")))][-1].id' > retail_id.txt
          echo "RETAIL_ID=$(cat retail_id.txt)" >> $GITHUB_ENV

      - name: Inject Retail ID into pkgmeta.yaml
        run: |
          cp pkgmeta.yaml pkgmeta.yaml.bak
          awk -v id="$RETAIL_ID" '
            BEGIN { inserted = 0 }
            {
              print $0
              if (!inserted && $0 ~ /game-version:/) {
                print "    - " id "  # Auto-fetched latest retail version"
                inserted = 1
              }
            }' pkgmeta.yaml.bak > pkgmeta.yaml

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
