name: Release WoW Addon

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip addon folder
        run: |
          mkdir -p build
          cd RaidMount
          zip -r ../build/RaidMount.zip .
          cd ..

      - name: Upload to CurseForge
        uses: Kir-Antipov/mc-publish@v3
        with:
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 1204427
          curseforge-files: |
            build/RaidMount.zip
          curseforge-loaders: |
            - wow_retail
          curseforge-game-versions: |
            - 11200  # Placeholder for 11.2.0
            - 11107  # Placeholder for 11.1.7
          curseforge-changelog: ${{ github.event.release.body }}
          curseforge-game-version-filter: any
