name: Release WoW Addon

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Package and upload addon
        uses: wagoio/wago-action@v1
        with:
          addon-path: 'RaidMount'
          curseforge-id: '1204427'
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          game-version: 'retail'
