name: Release WoW Addon

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Package and upload addon
      uses: WowUpHub/release-wow-addon@v3
      with:
        addon-path: 'RaidMount'
        curseforge-id: '1204427'
        curseforge-token: ${{ a830dcd2-9e1d-46a9-bc68-6f6585d5dba8 }}
        wago-token: ${{ fJjOOawNq0HzaFGz6rppP74MAC3CMqIDcPHkb4rl }}
        game-version: 'retail'
