name: Release WoW Addon

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Zip addon folder
        run: |
          mkdir -p build
          cd RaidMount
          zip -r ../build/RaidMount.zip .
          cd ..

      - name: Upload to CurseForge
        uses: Kir-Antipov/mc-publish@v3
        with:
          curseforge-token: ${{ secrets.CURSEFORGE_TOKEN }}
          curseforge-id: 1204427
          files: build/*.zip
          game-version: wow_retail
          changelog: ${{ github.event.release.body }}
          changelog-type: markdown

