name: Full Addon Release

on:
  release:
    types: [published]

jobs:
  release:
    name: Build and Upload Release
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Debug Fetch versions response
        run: |
          curl -s -H "X-Api-Token: ${{ secrets.CURSEFORGE_TOKEN }}" https://wow.curseforge.com/api/game/versions > response.json
          head -30 response.json

      - name: Fetch latest Retail game version ID
        id: get-retail-id
        run: |
          # Fetch latest retail version ID matching semantic versioning (e.g. "10.0.7")
          RETAIL_ID=$(curl -s -H "X-Api-Token: ${{ secrets.CURSEFORGE_TOKEN }}" https://wow.curseforge.com/api/game/versions | \
            jq '[.[] | select(.flavor=="wow_retail" and (.name | test("^[0-9]+\\.[0-9]+\\.[0-9]+$")))][-1].id' -r)
          echo "RETAIL_ID=$RETAIL_ID" >> $GITHUB_ENV
          echo "Latest retail game version ID is $RETAIL_ID"

      - name: Inject Retail ID into pkgmeta.yaml
        run: |
          cp pkgmeta.yaml pkgmeta.yaml.bak
          awk -v id="$RETAIL_ID" '
            BEGIN { inserted=0; in_cf=0 }
            /^curseforge:/ { in_cf=1; print; next }
            in_cf && /^[[:space:]]*game-versions:/ {
              print "  game-versions:"
              print "    - " id "  # Auto-fetched latest retail version"
              inserted=1
              # Skip existing lines starting with dash (old versions)
              while(getline && /^[[:space:]]*-/) {}
              if(length($0)) print
              next
            }
            in_cf && !inserted && /^[[:space:]]*game-version:/ {
              print "  game-versions:"
              print "    - " id "  # Auto-fetched latest retail version"
              inserted=1
              next
            }
            {
              print
            }
            END {
              if (!inserted && in_cf) {
                print "  game-versions:"
                print "    - " id "  # Auto-fetched latest retail version"
              }
            }
          ' pkgmeta.yaml.bak > pkgmeta.yaml

      - name: Show updated pkgmeta.yaml
        run: cat pkgmeta.yaml

      - name: Run BigWigs Packager
        uses: BigWigsMods/packager@v2
        env:
          CF_API_KEY: ${{ secrets.CURSEFORGE_TOKEN }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          WOWI_API_TOKEN: ${{ secrets.WOWI_API_TOKEN }}
